- name: Start of playbook
  tasks:
    - name: Update the cache
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Fetch the Barchok-Kiposmet/yolo GitHub repository
      git:
        repo: https://github.com/Barchok-Kiposmet/yolo.git
        dest: /opt/yolo
        when: not repo_stat.stat.exists
